import PySimpleGUI as sg
import ImageJam
import base64
import numpy as np
# some useful variables
img_w = 500
img_h = 500
r_prev = 0
g_prev = 0
b_prev = 0
# set color theme
# sg.theme('darkteal5')
# py simple gui layout as generated by nested list
gui_layout = [[sg.Text('ImageJam by spacewaves', font=220, text_color="Silver")],
              [sg.Text('Import Image: '), sg.Input(), sg.FileBrowse(), sg.Button('Upload Image', key='UPLOAD_IMG')],
              [sg.Text('Red Value'), sg.Slider([-100, 100], orientation="horizontal", default_value=0, key='rSlider')],
              [sg.Text('Green Value'), sg.Slider([-100, 100], orientation="horizontal", default_value=0, key='gSlider')],
              [sg.Text('Blue Value'), sg.Slider([-100, 100], orientation="horizontal", default_value=0, key='bSlider')],
              [sg.Image("test_img.png", size=(img_w, img_h), key="MAIN_IMG", pad=(20, 20))],  # set the key in order to access the window element during the runtime loop
              [sg.Button('Advanced')],
              [sg.Text('copyright heady studios 2020', font=220, text_color="Silver")]]


# create the main window for the gui
window = sg.Window("ImageJam", gui_layout, margins=(100, 50))

# Event Loop to process "events" and get the "values" of the inputs
while True:
    event, values = window.read(timeout=100)
    if values[0] != '':
        # set the current image path
        cur_filepath = values[0]
        # r_val, g_val, b_val = values['ColorR'], values['ColorG'], values['ColorB']  # get the current slider values
        r_val, g_val, b_val = values['rSlider'], values['gSlider'], values['bSlider']
        if r_val != r_prev or g_val != g_prev or b_val != b_prev:
            # pass the current slider values to the colorizer
            image_update = ImageJam.set_color(cur_filepath, r_val, g_val, b_val)
            print(image_update)
            image_update.save('cur_img', format="png")
            # convert the image to base64 representation
            # cur_img_64 = base64.b64encode(np.asarray(image_update))
            # update the gui image
            window.Element('MAIN_IMG').update('cur_img', size=(img_w, img_h))
            # get rid of these
            #print(r_val, g_val, b_val)
            # if event == 'rSlider' or event == 'gSlider' or event == 'bSlider':
        r_prev, g_prev, b_prev = r_val, g_val, b_val
    if event == 'UPLOAD_IMG' and cur_filepath != ' ':
        window.Element('MAIN_IMG').update(cur_filepath)
    # slider colorizer listener awaiting changes to slider values

    if event == sg.WIN_CLOSED or event == 'Cancel':  # if user closes window or clicks cancel
        break
# on exit
window.close()
