import PySimpleGUI as sg
import ImageJam

# set color theme

# py simple gui layout as generated by nested list
gui_layout = [[sg.Text('ImageJam by spacewaves', font=220, text_color="Silver")],
              [sg.Text('Import Image: '), sg.Input(), sg.FileBrowse(), sg.Button('Upload Image', key='UPLOAD_IMG')],
              [sg.Text('Red Value'), sg.Slider([-100, 100], orientation="horizontal", key='ColorR')],
              [sg.Text('Green Value'), sg.Slider([-100, 100], orientation="horizontal", key='ColorG')],
              [sg.Text('Blue Value'), sg.Slider([-100, 100], orientation="horizontal", key='ColorB')],
              [sg.Image("test_img.png", size=(500, 500), key="MAIN_IMG")],  # set the key in order to access the window element during the runtime loop
              [sg.Button('Advanced')],
              [sg.Text('copyright heady studios 2020', font=220, text_color="Silver")]]


# create the main window for the gui
window = sg.Window("ImageJam", gui_layout, margins=(100, 50))

# Event Loop to process "events" and get the "values" of the inputs
while True:
    event, values = window.read()
    # set the current image path
    cur_filepath = values[0]
    if event == 'UPLOAD_IMG':
        window.Element('MAIN_IMG').update(cur_filepath)
    # slider colorizer listener awaiting changes to slider values
    if values['ColorR'] or values['ColorR'] or values['ColorR']:
        r_val, g_val, b_val = values['ColorR'], values['ColorG'], values['ColorB']  # get the current slider values
        # pass the current slider values to the colorizer
        ImageJam.set_color(cur_filepath, r_val, g_val, b_val)
        window.Element('MAIN_IMG').update(cur_filepath)
        print(r_val, g_val, b_val)
    if event == sg.WIN_CLOSED or event == 'Cancel':  # if user closes window or clicks cancel
        break

window.close()
